/**
 * Totais da nota (grupo `total/ICMSTot`), na ordem do layout. Valem para a NF-e
 * inteira e se repetem em cada linha de item — não some a coluna entre itens da
 * mesma nota.
 */
export const TOT_COLS = [
  "tot_vBC",
  "tot_vICMS",
  "tot_vICMSDeson",
  "tot_vFCPUFDest",
  "tot_vICMSUFDest",
  "tot_vICMSUFRemet",
  "tot_vFCP",
  "tot_vBCST",
  "tot_vST",
  "tot_vFCPST",
  "tot_vFCPSTRet",
  "tot_vProd",
  "tot_vFrete",
  "tot_vSeg",
  "tot_vDesc",
  "tot_vIPI",
  "tot_vIPIDevol",
  "tot_vOutro",
  "tot_vNF",
] as const;

export type TotColKey = (typeof TOT_COLS)[number];

/** Ordem das colunas (chaves internas) — fonte única. */
export const COLS = [
  "chNFe",
  "serie",
  "nNF",
  "natOp",
  "dhEmi",
  "tpEmis",
  "tpNF",
  "indPres_raw",
  "indPres",
  "finNFe_raw",
  "finNFe",
  "emit_CNPJ",
  "emit_xNome",
  "emit_UF",
  "emit_IE",
  "emit_IEST",
  "dest_CNPJ",
  "dest_xNome",
  "dest_UF",
  "dest_IE",
  "cProd",
  "cEAN",
  "xProd",
  "NCM",
  "CFOP",
  "uCom",
  "qCom",
  "vUnCom",
  "vProd",
  "vOutro",
  "CSOSN/CST",
  "orig",
  "modBC",
  "vBC",
  "pICMS",
  "vICMS",
  "vBC_IPI",
  "pIPI",
  "vIPI",
  "pPIS",
  "vPIS",
  "pCOFINS",
  "vCOFINS",
  ...TOT_COLS,
  "Alerta Fiscal",
  "Descrição",
] as const;

export type ColKey = (typeof COLS)[number];

export type NfeRow = Record<ColKey, string>;

export const HEADER_MAP: Record<ColKey, string> = {
  chNFe: "Chave NFe",
  serie: "Série",
  nNF: "Nº NF",
  natOp: "Nat Op.",
  dhEmi: "Emissão",
  tpEmis: "Tipo Emissão",
  tpNF: "tp OP",
  indPres: "Presença do Comprador",
  indPres_raw: "indPres (raw)",
  finNFe: "Finalidade da NF-e",
  finNFe_raw: "finNFe (raw)",
  emit_CNPJ: "CNPJ Emit.",
  emit_xNome: "Nome Emit.",
  emit_UF: "UF Emit.",
  emit_IE: "IE Emit.",
  emit_IEST: "IEST Emit.",
  dest_CNPJ: "CNPJ Dest.",
  dest_xNome: "Nome Dest.",
  dest_UF: "UF Dest.",
  dest_IE: "IE Dest.",
  cProd: "Cod. Prod.",
  cEAN: "EAN",
  xProd: "Desc. Prod.",
  NCM: "NCM",
  CFOP: "CFOP",
  uCom: "Unidade",
  qCom: "Qtde",
  vUnCom: "Vlr Unit.",
  vProd: "Vlr Total",
  vOutro: "Outros Vlr",
  "CSOSN/CST": "CST",
  orig: "Origem",
  modBC: "Mod BC",
  vBC: "BC ICMS",
  pICMS: "Aliq ICMS",
  vICMS: "Vlr ICMS",
  vBC_IPI: "BC IPI",
  pIPI: "Aliq IPI",
  vIPI: "Vlr IPI",
  pPIS: "Aliq PIS",
  vPIS: "Vlr PIS",
  pCOFINS: "Aliq COFINS",
  vCOFINS: "Vlr COFINS",
  tot_vBC: "Tot Base Calc ICMS",
  tot_vICMS: "Tot ICMS",
  tot_vICMSDeson: "ICMS Deson.",
  tot_vFCPUFDest: "FCP Dest.",
  tot_vICMSUFDest: "ICMS UF Dest.",
  tot_vICMSUFRemet: "ICMS UF Remet.",
  tot_vFCP: "FCP",
  tot_vBCST: "BC ST",
  tot_vST: "Vlr ST",
  tot_vFCPST: "FCP ST",
  tot_vFCPSTRet: "FCP ST Ret",
  tot_vProd: "Tot Prod ICMS",
  tot_vFrete: "Frete",
  tot_vSeg: "Seguro",
  tot_vDesc: "Desconto",
  tot_vIPI: "IPI",
  tot_vIPIDevol: "IPI Devol.",
  tot_vOutro: "Outros",
  tot_vNF: "Valor NF",
  "Alerta Fiscal": "Alerta Fiscal",
  Descrição: "Descrição",
};

export function emptyRow(): NfeRow {
  const r = {} as NfeRow;
  for (const c of COLS) r[c] = "";
  return r;
}
